#!/bin/python3

from dbm.ndbm import library
import os
from unicodedata import name
gitignore = "*.o\n*.out\n*.lib\n*.a\n*.gcno\n*.gcda\n.vscode\n"
lib_makefile_content = "##\n## EPITECH PROJECT, 2022\n## $1\n## File description:\n## Makefile for lib $2.\n##\n\nSRC=	$(wildcard *.c)\n\nNAME=	lib$2.a\n\nLIB_DEST=	../\n\nOBJ=	$(SRC:.c=.o)\n\nall:	$(NAME)\n\n$(NAME):	$(OBJ)\n	ar rc $(NAME) $(OBJ)\n	cp $(NAME) $(LIB_DEST)\n\nclean:\n	rm -f $(OBJ)\n\nfclean: clean\n	rm -f $(NAME)\n	rm -f ../$(NAME)\n\nre: fclean all\n"

ascii_logo = ''' ____________________________________________
/                   _____                    \\
|                  |  __ \                   |
|   _ __ ___  _   _| |__) |___ _ __   ___    |
|  | '_ ` _ \| | | |  _  // _ \ '_ \ / _ \   |
|  | | | | | | |_| | | \ \  __/ |_) | (_) |  |
|  |_| |_| |_|\__, |_|  \_\___| .__/ \___/   |
|              __/ |          | |            |
|             |___/           |_|            |
\____________________________________________/
'''
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

affirmative = ["o", "y", "oui", "yes"]
print(bcolors.OKBLUE + ascii_logo + bcolors.BOLD + "\nThe easiest way to init your {EPITECH.} repository.\n"+ bcolors.ENDC)

infos = {
    "name" : ["Binary name", "*", ""],
    "lib" : ["compiled lib ?", "o/n", False],
    "tests" : ["Unit tests", "o/n", False],
}


phony = ".PHONY: all clean fclean re"

for i in infos:
    rep = input(bcolors.HEADER + infos[i][0]+": ")
    if infos[i][1] == "*":
        infos[i][2] = rep
    elif infos[i][1] == "o/n":
        if rep.lower() in affirmative:
            infos[i][2] = True
infos["name"][2] = infos["name"][2].lower().replace(" ", "_")

makefile = '''##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## Project's main makefile
##

SRC	=	$(wildcard *.c) $(wildcard src/*.c)

OBJ	=	$(SRC:.c=.o)

NAME	=	''' + infos["name"][2] + '''

TESTS	=	-lcriterion --coverage

LIB	=	'''

lib_actions = ""

repo_name = os.getcwd().split("/")[-1]
if not os.path.exists("src"):
    os.mkdir("src")
    project_file = open("src/%s.c" % infos["name"][2], "w+")
    project_file.write("/*\n** EPITECH PROJECT, 2022\n** " + repo_name + "\n** File description:\n** Main file of " + infos["name"][2] + " project.\n*/\n\nint " + infos["name"][2] + "(int argc, char **argv)\n{\n    return (0);\n}\n")
if not os.path.exists("include"):
    os.mkdir("include")
includes = ""
main_file = open('main.c', 'w+')
main_file.write("/*\n** EPITECH PROJECT, 2022\n** " + repo_name + "\n** File description:\n** Main file of " + infos["name"][2] + " project.\n*/\n\nint main(int argc, char **argv)\n{\n    return " + infos["name"][2] + "(argc, argv);\n}\n")
main_file.close()

if infos["lib"][2] == False:
    lib_name = "library"
    if not os.path.exists("lib"):
        os.mkdir("lib")
    if not os.path.exists("include/include.h"):
        include_file = open("include.include.h", "w+")
        include_file.write("/*\n** EPITECH PROJECT, 2022\n** " + repo_name + "\n** File description:\n** \n*/\n\n#ifndef " + lib_name.upper() + "_H_\n    #define " + lib_name.upper() + "\n\n" + infos["name"][2] + "(int argc, char **argv);\n\n#endif\n")

if infos["lib"][2]:
    makefile += "	-L./lib -l" + " -l".join("library")
    lib_actions = "			make$ -C./lib/" + "\n			make$ -C./lib/".join("library")+ "\n"
    if not os.path.exists("lib"):
        os.mkdir("lib")

    lib_name = "library"
    if not os.path.exists("lib/"+lib_name):
        os.mkdir("lib/"+lib_name)
        fantome = open('include/.fantome', 'w+')
        fantome.close()
        lib_makefile = open('lib/'+lib_name+'/Makefile', 'w+')
        lib_makefile.write(lib_makefile_content.replace("$1", repo_name).replace("$2", lib_name))
        lib_makefile.close()
        lib_header = open('include/include.h', 'w+')
        lib_header.write("/*\n** EPITECH PROJECT, 2021\n** " + repo_name + "\n** File description:\n** Header file for lib " + lib_name + ".\n*/\n\n#ifndef "+lib_name.upper()+"_H_\n    #define "+lib_name.upper()+"_H_\n\n#endif")
        includes += ("\n#include \"" + lib_name + ".h\"")
        lib_header.close()
    if len(includes) > 0:
        includes += '\n'

lib_header = open('include/'+infos["name"][2]+'.h', 'w+')
lib_header.write("/*\n** EPITECH PROJECT, 2021\n** " + repo_name + "\n** File description:\n** Header file for project " + infos["name"][2] + ".\n*/\n"+includes+"\n#ifndef "+infos["name"][2].upper()+"_H_\n    #define "+infos["name"][2].upper()+"_H_\n\n#endif")
lib_header.close()
makefile += "\n\n"

makefile += "${NAME}:	${OBJ}\n" + lib_actions.replace("make$", "make") + "			gcc -o ${NAME} ${OBJ} $(LIB)\n\nall :		${NAME}\n\n"
makefile += "clean:\n			rm -f ${OBJ}\n" + lib_actions.replace("make$", "make clean") + "\n\n"
makefile += "fclean:	clean\n			rm -f ${NAME}\n" + lib_actions.replace("make$", "make fclean") + "\n"
if infos["tests"][2]:
    makefile += "			rm -f *.gcno *.gcda unit_tests\n"
makefile += "\nre:		fclean all\n\n"

if infos["tests"][2]:
    makefile += "unit_tests:		re\n		gcc -o unit_tests $(SRC) tests/tests_" + infos["name"][2] + ".c $(LIB) $(TESTS)\n\n"
    makefile += "tests_run:		unit_tests\n		./unit_tests\n\n"
    phony += " unit_tests tests_run"
    if not os.path.exists("tests"):
        os.mkdir("tests")
        tests = open('tests/tests_'+infos["name"][2]+'.c', 'w+')
        tests.write("/*\n** EPITECH PROJECT, 2021\n** " + repo_name + "\n** File description:\n** Unit tests for " + infos["name"][2] + " project.\n*/\n\n#include <criterion/criterion.h>\n#include <criterion/redirect.h>\n#include \"../include/"+infos["name"][2]+".h\"\n\n")
        tests.close()
makefile += phony + "\n"

mfile = open('Makefile', 'w+')
mfile.write(makefile)
mfile.close()

gitign = open('.gitignore', 'w+')
gitign.write(gitignore)
gitign.close()
